<?php

namespace App\Http\Requests;

use Illuminate\Contracts\Validation\Validator;
use Illuminate\Foundation\Http\FormRequest;

class RestaurantValidatorRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'name' =>'required|min:3|max:30',
            'image' => 'image',
            'category' => 'exists:categories,id',
        ];
    }

    public function failedValidation(Validator $validator)
    {
        var_dump($_POST);
        var_dump($validator->errors()->toArray());die;
        parent::failedValidation($validator); // TODO: Change the autogenerated stub

    }
}
