<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="login.php" method="post">
    <label for="">Логин</label>
    <input type="text" name="login">
    <label for="">email</label>
    <input type="text" name="email">
    <label for="">Пароль</label>
    <input type="text" name="password">
    <input type="submit" value="REGISTER">
</form>

</body>
</html>